# Generated by Django 4.2.16 on 2025-06-02 07:04

import awr_upload.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='用户定义的报告名称', max_length=200, verbose_name='报告名称')),
                ('description', models.TextField(blank=True, db_comment='用户对报告的描述信息', null=True, verbose_name='报告描述')),
                ('original_filename', models.CharField(db_comment='上传时的原始文件名', max_length=255, verbose_name='原始文件名')),
                ('file_path', models.FileField(db_comment='AWR文件在服务器上的存储路径', max_length=500, upload_to=awr_upload.models.awr_file_upload_path, verbose_name='文件路径')),
                ('file_size', models.PositiveBigIntegerField(db_comment='文件大小（字节）', verbose_name='文件大小')),
                ('file_hash', models.CharField(db_comment='文件SHA-256哈希值，用于去重和完整性校验', max_length=64, unique=True, verbose_name='文件哈希')),
                ('oracle_version', models.CharField(blank=True, db_comment='Oracle数据库版本，如11g、12c、19c', max_length=20, null=True, verbose_name='Oracle版本')),
                ('instance_name', models.CharField(blank=True, db_comment='Oracle实例名称', max_length=50, null=True, verbose_name='实例名称')),
                ('host_name', models.CharField(blank=True, db_comment='数据库服务器主机名', max_length=100, null=True, verbose_name='主机名')),
                ('database_id', models.CharField(blank=True, db_comment='Oracle数据库ID', max_length=20, null=True, verbose_name='数据库ID')),
                ('instance_number', models.PositiveSmallIntegerField(blank=True, db_comment='RAC环境下的实例编号', null=True, verbose_name='实例编号')),
                ('snapshot_begin_time', models.DateTimeField(blank=True, db_comment='AWR报告快照的开始时间', null=True, verbose_name='快照开始时间')),
                ('snapshot_end_time', models.DateTimeField(blank=True, db_comment='AWR报告快照的结束时间', null=True, verbose_name='快照结束时间')),
                ('snapshot_duration_minutes', models.PositiveIntegerField(blank=True, db_comment='AWR快照时间范围（分钟）', null=True, verbose_name='快照时长(分钟)')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('validating', '校验中'), ('validated', '校验完成'), ('parsing', '解析中'), ('parsed', '解析完成'), ('analyzing', '分析中'), ('completed', '完成'), ('failed', '失败')], db_comment='报告处理流程状态', default='uploaded', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, db_comment='处理失败时的错误详情', null=True, verbose_name='错误信息')),
                ('tags', models.JSONField(blank=True, db_comment='用户定义的报告标签', default=list, verbose_name='标签')),
                ('category', models.CharField(blank=True, choices=[('production', '生产环境'), ('test', '测试环境'), ('development', '开发环境'), ('staging', '预发布环境')], db_comment='数据库环境分类', max_length=50, null=True, verbose_name='环境分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='报告记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='报告记录最后更新时间', verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(db_comment='上传此报告的用户', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': 'AWR报告',
                'verbose_name_plural': 'AWR报告',
                'db_table': 'awranalyzer_awr_report',
                'db_table_comment': 'AWR报告主表',
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='awranalyzer_uploade_db50f8_idx'), models.Index(fields=['status'], name='awranalyzer_status_fdae9c_idx'), models.Index(fields=['oracle_version'], name='awranalyzer_oracle__126834_idx'), models.Index(fields=['instance_name'], name='awranalyzer_instanc_c0ed66_idx'), models.Index(fields=['snapshot_begin_time'], name='awranalyzer_snapsho_e3826e_idx'), models.Index(fields=['category'], name='awranalyzer_categor_8a814f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='awrreport',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gt', 0)), name='positive_file_size'),
        ),
    ]
