# Generated by Django 4.2.16 on 2025-06-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparisons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awr_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='用户定义的导出任务名称', max_length=200, verbose_name='导出名称')),
                ('description', models.TextField(blank=True, db_comment='导出任务的详细描述', null=True, verbose_name='导出描述')),
                ('export_type', models.CharField(choices=[('report', '单个报告导出'), ('comparison', '对比分析导出'), ('batch_reports', '批量报告导出'), ('dashboard', '仪表盘导出'), ('custom_data', '自定义数据导出')], db_comment='导出的内容类型', max_length=50, verbose_name='导出类型')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], db_comment='导出文件的格式', max_length=20, verbose_name='导出格式')),
                ('export_config', models.JSONField(blank=True, db_comment='导出的详细配置参数', default=dict, verbose_name='导出配置')),
                ('data_filters', models.JSONField(blank=True, db_comment='数据筛选和过滤条件', default=dict, verbose_name='数据过滤器')),
                ('template_settings', models.JSONField(blank=True, db_comment='导出模板的配置设置', default=dict, verbose_name='模板设置')),
                ('include_sections', models.JSONField(blank=True, db_comment='导出中包含的数据章节', default=list, verbose_name='包含章节')),
                ('exclude_sections', models.JSONField(blank=True, db_comment='导出中排除的数据章节', default=list, verbose_name='排除章节')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_comment='导出任务的处理状态', default='pending', max_length=20, verbose_name='导出状态')),
                ('progress_percentage', models.PositiveSmallIntegerField(db_comment='导出处理的进度百分比', default=0, verbose_name='进度百分比')),
                ('error_message', models.TextField(blank=True, db_comment='导出失败时的错误详情', null=True, verbose_name='错误信息')),
                ('output_filename', models.CharField(blank=True, db_comment='生成的导出文件名', max_length=255, null=True, verbose_name='输出文件名')),
                ('output_file_path', models.FileField(blank=True, db_comment='导出文件在服务器上的存储路径', max_length=500, null=True, upload_to=exports.models.export_file_upload_path, verbose_name='输出文件路径')),
                ('file_size', models.PositiveBigIntegerField(blank=True, db_comment='导出文件大小（字节）', null=True, verbose_name='文件大小')),
                ('file_hash', models.CharField(blank=True, db_comment='导出文件的SHA-256哈希值', max_length=64, null=True, verbose_name='文件哈希')),
                ('is_public', models.BooleanField(db_comment='导出文件是否公开可访问', default=False, verbose_name='是否公开')),
                ('download_count', models.PositiveIntegerField(db_comment='文件被下载的次数', default=0, verbose_name='下载次数')),
                ('expires_at', models.DateTimeField(blank=True, db_comment='导出文件的过期时间', null=True, verbose_name='过期时间')),
                ('auto_cleanup', models.BooleanField(db_comment='过期后是否自动清理文件', default=True, verbose_name='自动清理')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='导出任务创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='导出任务最后更新时间', verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, db_comment='导出处理开始时间', null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, db_comment='导出处理完成时间', null=True, verbose_name='完成时间')),
                ('awr_report', models.ForeignKey(blank=True, db_comment='导出关联的AWR报告（单报告导出时）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='awr_upload.awrreport', verbose_name='AWR报告')),
                ('comparison', models.ForeignKey(blank=True, db_comment='导出关联的对比分析（对比导出时）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='comparisons.reportcomparison', verbose_name='对比分析')),
                ('created_by', models.ForeignKey(db_comment='创建此导出任务的用户', on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_exports', to=settings.AUTH_USER_MODEL, verbose_name='共享用户')),
            ],
            options={
                'verbose_name': '导出记录',
                'verbose_name_plural': '导出记录',
                'db_table': 'awranalyzer_export_record',
                'db_table_comment': '导出记录表',
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='awranalyzer_created_84ca53_idx'), models.Index(fields=['status'], name='awranalyzer_status_ff18db_idx'), models.Index(fields=['export_type', 'export_format'], name='awranalyzer_export__e817c3_idx'), models.Index(fields=['expires_at'], name='awranalyzer_expires_1b36fe_idx'), models.Index(fields=['awr_report'], name='awranalyzer_awr_rep_e85330_idx'), models.Index(fields=['comparison'], name='awranalyzer_compari_63f9eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='exportrecord',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gte', 0)), name='non_negative_file_size'),
        ),
        migrations.AddConstraint(
            model_name='exportrecord',
            constraint=models.CheckConstraint(check=models.Q(('download_count__gte', 0)), name='non_negative_download_count'),
        ),
    ]
